### ISSUE TITLE
大陆用户，无法启动程序，错误LOG显示urlib的连接问题，已经启用VPN且打开本地端口，可能程序还需要在源码里直接添加proxy

### ISSUE THREAD

**Issue by RandyLuaW** [anonymousException/renpy-translator#22]
错误LOG：
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 486, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\connectionpool.py", line 847, in urlopen
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 338, in get_region_of_server
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 73, in get
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 59, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 589, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 703, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\main.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\extraction_official_form.py", line 13, in <module extraction_official_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\editor_form.py", line 24, in <module editor_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\renpy_translate.py", line 15, in <module renpy_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translator_translate.py", line 7, in <module translator_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\__init__.py", line 5, in <module translators>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5596, in <module translators.server>
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5324, in __init__
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 344, in get_region_of_server
translators.server.TranslatorError: Unable to connect the Internet.

urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 486, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\connectionpool.py", line 847, in urlopen
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 338, in get_region_of_server
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 73, in get
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 59, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 589, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 703, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\main.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\extraction_official_form.py", line 13, in <module extraction_official_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\editor_form.py", line 24, in <module editor_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\renpy_translate.py", line 15, in <module renpy_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translator_translate.py", line 7, in <module translator_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\__init__.py", line 5, in <module translators>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5596, in <module translators.server>
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5324, in __init__
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 344, in get_region_of_server
translators.server.TranslatorError: Unable to connect the Internet.

urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 486, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\connectionpool.py", line 847, in urlopen
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 338, in get_region_of_server
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 73, in get
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 59, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 589, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 703, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\main.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\extraction_official_form.py", line 13, in <module extraction_official_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\editor_form.py", line 24, in <module editor_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\renpy_translate.py", line 15, in <module renpy_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translator_translate.py", line 7, in <module translator_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\__init__.py", line 5, in <module translators>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5596, in <module translators.server>
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5324, in __init__
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 344, in get_region_of_server
translators.server.TranslatorError: Unable to connect the Internet.

urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 486, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\connectionpool.py", line 847, in urlopen
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 338, in get_region_of_server
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 73, in get
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 59, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 589, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 703, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\main.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\extraction_official_form.py", line 13, in <module extraction_official_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\editor_form.py", line 24, in <module editor_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\renpy_translate.py", line 15, in <module renpy_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translator_translate.py", line 7, in <module translator_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\__init__.py", line 5, in <module translators>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5596, in <module translators.server>
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5324, in __init__
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 344, in get_region_of_server
translators.server.TranslatorError: Unable to connect the Internet.

urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 486, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\connectionpool.py", line 847, in urlopen
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 338, in get_region_of_server
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 73, in get
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 59, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 589, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 703, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\main.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\extraction_official_form.py", line 13, in <module extraction_official_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\editor_form.py", line 24, in <module editor_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\renpy_translate.py", line 15, in <module renpy_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translator_translate.py", line 7, in <module translator_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\__init__.py", line 5, in <module translators>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5596, in <module translators.server>
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5324, in __init__
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 344, in get_region_of_server
translators.server.TranslatorError: Unable to connect the Internet.

urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 486, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\connectionpool.py", line 847, in urlopen
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 338, in get_region_of_server
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 73, in get
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 59, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 589, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 703, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\main.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\extraction_official_form.py", line 13, in <module extraction_official_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\editor_form.py", line 24, in <module editor_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\renpy_translate.py", line 15, in <module renpy_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translator_translate.py", line 7, in <module translator_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\__init__.py", line 5, in <module translators>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5596, in <module translators.server>
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5324, in __init__
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 344, in get_region_of_server
translators.server.TranslatorError: Unable to connect the Internet.

urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 486, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\connectionpool.py", line 847, in urlopen
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 338, in get_region_of_server
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 73, in get
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\api.py", line 59, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 589, in request
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\sessions.py", line 703, in send
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /ip (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\main.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\extraction_official_form.py", line 13, in <module extraction_official_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\editor_form.py", line 24, in <module editor_form>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\renpy_translate.py", line 15, in <module renpy_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translator_translate.py", line 7, in <module translator_translate>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\__init__.py", line 5, in <module translators>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5596, in <module translators.server>
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 5324, in __init__
  File "C:\Users\RANDYL~1\AppData\Local\Programs\RENPYT~1\translators\server.py", line 344, in get_region_of_server
translators.server.TranslatorError: Unable to connect the Internet.

**Comment by anonymousException** [comment]
已修复
